### ISSUE TITLE
how to use getSelectedNode() ???

### ISSUE THREAD

**Issue by moeali1010** [scalia/vuejs-tree#10]
<Tree id="my-tree-id" ref="my-tree-ref" :custom-options="myCustomOptions" :custom-styles="myCustomStyles" :nodes="treeDisplayData" ></Tree>

i want to get selected node , in documentation you said use getSelectedNode() , but how ??

**Comment by vinz3872** [comment]
Hi,

First you need to get the tree instance with `this.$refs['your-tree-ref']` and then call the function `getSelectedNode()` on it
There's a [codesandbox ](https://codesandbox.io/s/vue-template-lmbyx) example if you want in the readme
