### ISSUE TITLE
how to add icon to tree

### ISSUE THREAD

**Issue by moeali1010** [scalia/vuejs-tree#12]
i tried 

 computed: {
    myCustomStyles() {
      return {
      icon:"folder",

but it doesn't work  , I'm using material design icons ,

also i tried path of image 

 computed: {
    myCustomStyles() {
      return {
      icon:"assets/images/folder.png",

it doesn't work also

**Comment by vinz3872** [comment]
Hi,

if you want to change the 'folder' icon, you need to use the key `selectIcon`
for example:
```js
myCustomStyles() {
  return {
    selectIcon: {
      class: 'folder_icon',
      active: {
        class: 'folder_icon_active',
      }
    },
  };
}

```

**Comment by elC0mpa** [comment]
I have a question related to this. I am using material design icons in my proyect. Whenever I need a folder icon, I just specify it giving ```folder``` to icon type
I tried what you said previously and it worked, but I want to use these icons from materia design, could you explain me if this is possible by using this package?
In case it won't be possible, which icons are ready to be used within this package?

**Comment by vinz3872** [comment]
Hi, the "icons" i use are defined [here](https://github.com/scalia/vuejs-tree/blob/eb08c294a431fb32182e28bd5b185792b0c698cb/src/components/TreeRow.vue#L398)

If you want to use other icons, you can overwrite the class and the style like this:
```js
selectIcon: {
  class: 'folder_icon',
  style: {
    color: '#007AD5'
  },
  active: {
    class: 'folder_icon_active',
    style: {
      color: '#2ECC71'
    }
  }
},
```

**Comment by Leupol17** [comment]
Hi, I have a question, I need to change the Icons individually, for each node, this is possible? thanks!!
