### ISSUE TITLE
Cannot set node property

### ISSUE THREAD

**Issue by clementlefevre** [scalia/vuejs-tree#20]
First of all, great package !
How can i activate the `checkable` property per node ?
According to the doc, when using `checkable:false`, the row should not be checkable.
see https://codesandbox.io/s/vue-template-forked-olh0u?file=/src/components/TreeExample.vue for a reproducible example.

Thanks a lot for your time,

Cheers,

Clement.

**Comment by vinz3872** [comment]
Hi,

Indeed, i accidentally removed the code when i reworked the params. :pray: 

I added it back in the [v2.0.1](https://github.com/scalia/vuejs-tree/releases/tag/v2.0.1)

**Comment by clementlefevre** [comment]
Thanks, it works with the v2.0.1 !
