### ISSUE TITLE
[New Feature/Pre-Pull Request] Ability to specify 'text' and 'nodes' key names

### ISSUE THREAD

**Issue by chrisreedtech** [scalia/vuejs-tree#24]
@vinz3872 
Great package. It has covered more of my needs than any other tree package/component I've tried yet.
I was struggling with the need for all the data's text to be in a field named 'text' and the 'children' being named 'nodes'. 

I'm using Laravel as a backend and it was quite convenient to use the child collection names from the database. 

I haven't contributed to any open source project in many years so my apologies for needing some guidance here. 

I forked this project and added this functionality to a new branch. 
I wanted to open a discussion before submitting a pull request. 
I'm wasn't sure what information you'd be looking for in that request or if you're even open to pull requests much less this feature.

If so, I implemented this functionality by adding two properties to both Tree.vue and TreeRow.vue. 
These are 'nodesName' and 'textName'. 
I tried to copy the existing styling / naming but I can understand if you want to rename these.

These two properties default to the existing name used in the code so they are backwards compatible (omitting them). 
All references to `node.nodes` have been changed to `node[nodesName]`. 
This effectively allows for dynamic naming of the nodes child container.

I realize now I should have made a much better commit message but hopefully the information in this issue will suffice.
[My Fork with 'Named Fields'](https://github.com/chrisreedtech/vuejs-tree/commit/9c710dfa96b86bcfa3c0e07b200e75be0603fede)

Open to any input you have on this. Thanks for your time!

**Comment by vinz3872** [comment]
Hi, it's a great idea !

You can create a PR, i'll merge it as long as the tests (jest) still pass :)
