### ISSUE TITLE
[Feature request] Displaying partially selected parent checkbox as semi-checked

### ISSUE THREAD

**Issue by Viisut** [scalia/vuejs-tree#25]
I couldn't find a way of configuring the component to display some kind of filled checkbox when at least one, but not all of the children elements are checked. If this is already possible then maybe someone could give a short explanation on how to achieve this kind of behaviour.

![image](https://user-images.githubusercontent.com/12573149/105869124-9077c680-5fff-11eb-8eb7-7b0615791618.png)

**Comment by vinz3872** [comment]
Hi, for now it's not possible to achieve that.

We'd to replace the checkbox's input in the TreeRow.vue file to allow the new state and check the node's children in the mounted function

**Comment by adityagoel28** [comment]
Hii, I also want this feature, request you to please add the feature for displaying partially selected parent checkbox as semi-checked.
Thank you.
