### ISSUE TITLE
Treedata is not dynamic

### ISSUE THREAD

**Issue by vidyakin** [scalia/vuejs-tree#26]
When I add or delete node, tree doesn't update, and I need to collapse and expand the node where changing was.
If I delete node, I need seek parent node and collapse/expand it again. 
What I'm doing wrong? (

**Comment by vinz3872** [comment]
Hi, i've update the readme's [example](https://codesandbox.io/s/vue-template-lmbyx?file=/src/components/TreeExample.vue) with a working 'add' and 'remove' function.
Can you try this implementation and tell me if the issue still persist ?
