### ISSUE TITLE
toggleExpanded event don't retrun the node expanded

### ISSUE THREAD

**Issue by jonathancohen0726** [scalia/vuejs-tree#27]
My options are like this : 
`myCustomOptions() {
        return {
          treeEvents: {
            expanded: {
              state: true,
              fn: this.myExpandedFunction,
            },
            collapsed: {
              state: false,
              fn: null,
            },
            selected: {
              state: false,
              fn: null,
            },
            checked: {
              state: true,
              fn: null,
            }
          },
          events: {
            expanded: {
              state: true,
              fn: null,
            },
            selected: {
              state: false,
              fn: null,
            },
            checked: {
              state: false,
              fn: null,
            },
            editableName: {
              state: false,
              fn: null,
              calledEvent: null,
            }
          },
          addNode: { state: false, fn: null, appearOnHover: false },
          editNode: { state: true, fn: null, appearOnHover: true },
          deleteNode: { state: true, fn: null, appearOnHover: true },
          showTags: true,
        };
      }`

 Simple console.log of nodeId and state.
`myExpandedFunction: function (nodeId, state) {
        console.log(nodeId);
        console.log(state);
      },`

Give me undefined, and true

**Comment by vinz3872** [comment]
Hi,
do you have an 'id' key on you nodes ? (you can check an exemple [here](https://codesandbox.io/s/vue-template-lmbyx) )
