### ISSUE TITLE
Event when node name is clicked

### ISSUE THREAD

**Issue by elC0mpa** [scalia/vuejs-tree#28]
First of all, I would like to say I think this is  a great component, I have been using it since long time ago. I would like to know if there is any way to listen for an event when a node name is clicked

![image](https://user-images.githubusercontent.com/53531665/110549474-dfda0800-8110-11eb-99d4-021517c1a410.png)
This is a node I am using, if I click in the right side of its name, selected event is fired, if I click in the left side, the expanded event is fired, this is perfect but...

Is there any event which could be listened to if the node name is clicked?
Thanks in advance

**Comment by JeffWinder** [comment]
this worked for me. In your computed myCustomOptions:
```
customSelected: {
            state: true,
            fn: this.onSelected
          },
          editableName: {
            state: true,
            calledEvent: 'customSelected'
          }
```
In your methods:
```
onSelected: function(node) {
   console.log(node.id)
}
```

**Comment by vinz3872** [comment]
Hi,

You can also use the `fn` key, like this:
```js
editableName: {
  state: true,
  fn: this.myCustomFunction,
},
```

and the method
```js
myCustomFunction: function(node) {
  console.log(node.id);
},
```

**Comment by elC0mpa** [comment]
Thanks @vinz3872 @JeffWinder, now my problem is solved!!!!
