### ISSUE TITLE
I can't use your component.

### ISSUE THREAD

**Issue by talapai** [scalia/vuejs-tree#3]
```
TypeError: Cannot read property 'checked' of undefined
```
in line 150 if file TreeRow.vue.
Here ` } else if (this.parentNode.state.checked) {`

---

I use example node data. TreeOptions are empty object.
My template:
```
<div class="categories-tree">
                <tree id="categoriesTree" :custom-options="treeOptions" :nodes="nodes"></tree>
              </div>
```
My singlefile component file is attached
[FindAndReplace.zip](https://github.com/scalia/vuejs-tree/files/2175789/FindAndReplace.zip)

**Comment by vinz3872** [comment]
I fix it in the commit 4c8c187ea0e597b429218cb479761d6f4049058f.
You just have to update the package with npm update vuejs-tree or yarn upgrade vuejs-tree.
