### ISSUE TITLE
getSelectedNode doesnt work

### ISSUE THREAD

**Issue by JGamboa** [scalia/vuejs-tree#30]
I gave me and array of undefineds.

this.$refs['my-tree'].getSelectedNode()

![imagen](https://user-images.githubusercontent.com/4482664/112900435-e0374480-90b9-11eb-97f1-6957f9d8f516.png)

**Comment by vinz3872** [comment]
Hi, do you mean the `getCheckedNodes` function ? (to get the 3 nodes in your screenshot ?)
this function take 2 parameters:
- the first is the node's key you want to retrieve (it's mandatory)
- the second is a boolean to get the response as an array or a hash (it's optional)

i've updated the exemple [here](https://codesandbox.io/s/vue-template-lmbyx?file=/src/components/TreeExample.vue:2868-2932) if you want
