### ISSUE TITLE
TypeError: Cannot set property 'expanded' of undefined occurs after data change

### ISSUE THREAD

**Issue by bustarice** [scalia/vuejs-tree#8]
`[Vue warn]: Error in v-on handler: "TypeError: Cannot set property 'expanded' of undefined"`

I get this error after I have made change to the nodes data such as deleting or adding any node.

When I refresh the page and try to expand or collapse the error doesn't happen. It is only when a change has occurred.

Any way for me to fix this?

**Comment by bustarice** [comment]
I forgot to add the state.expanded into my array. Working now.

**Comment by nickbien** [comment]
bumping into this, @bustarice thanks, adding state was also the solution to my issue.
